#!/bin/bash
# ExtractProteinMutations 0.0.1
# Generated by dx-app-wizard.
#
# Basic execution pattern: Your app will run on a single machine from
# beginning to end.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

main() {

    echo "Value of vcf_in: '$vcf_in'"	


	dx download "${vcf_in}"
	
	mkdir -p analysis
	
    mv "${vcf_in_name}" analysis
    ls analysis/
	
	
	name="${vcf_in_name}"
    outfile="${name%%.*}_data.csv"
    outfile2="${name%%.*}_dict.csv"


    #docker run -v $PWD/analysis:/analysis malitsadok/image2:1 sh -c "tabix -p vcf /analysis/'${vcf_in_name}'"

    #docker run -v $PWD/analysis:/analysis malitsadok/image2:1 sh -c "java -Xmx8G -jar /app/snpEff/snpEff.jar -noStats -no-intergenic -no-downstream -no-upstream -no-intron -no-utr -onlyProtein -canon GRCh38.99 /analysis/'${vcf_in_name}' > /analysis/$outfile3"
    docker run -v $PWD/analysis:/analysis malitsadok/image2:1 sh -c "java -Xmx8G -jar /app/snpEff/snpEff.jar -noStats -no-intergenic -no-downstream -no-upstream -no-intron -no-utr -onlyProtein -canon GRCh38.99 /analysis/'${vcf_in_name}' > /analysis/anotated.vcf && java -Xmx8G -jar /app/snpEff/SnpSift.jar  filter \"(ANN[*].EFFECT has 'missense_variant') | (ANN[*].IMPACT = 'HIGH')\" /analysis/anotated.vcf > /analysis/anotated_filter.vcf &&  bgzip -c /analysis/anotated_filter.vcf >  /analysis/anotated_filter.vcf.gz && tabix  -p vcf /analysis/anotated_filter.vcf.gz && Rscript /get_analysis_data.R -f  /analysis/anotated_filter.vcf.gz"
    ls analysis/
	ls

    mv analysis/mutation.csv analysis/$outfile
	mv analysis/snv_dict.csv analysis/$outfile2 


	
   # mutation_file=$(dx upload analysis/$outfile --brief)
   # echo "mutation_file: $mutation_file"


   # dx-jobutil-add-output mutation_file "$mutation_file" --class=file
	
	
	mkdir  -p ~/out/results
    mv analysis/$outfile ~/out/results/
    mv analysis/$outfile2  ~/out/results/


	#mv analysis/$outfile3  ~/out/results/
    dx-upload-all-outputs
	
	
	
	

}
